import Editor, { type OnMount } from "@monaco-editor/react";
import type * as Monaco from "monaco-editor";
import { useCallback, useEffect, useRef, useState } from "react";
import { io, type Socket } from "socket.io-client";

type Participant = { clientId: string; username: string; online: boolean; isHost: boolean };
type DocumentState = { content: string; language: string; version: number };
type RoomState = { code: string; document: DocumentState; participants: Participant[] };
type Activity = { message: string; createdAt: string };
type Change = { rangeOffset: number; rangeLength: number; text: string };
type Credentials = { username: string; roomCode: string; passcode: string; clientId: string };
const serverUrl = import.meta.env.VITE_SERVER_URL ?? "http://localhost:3001";
const getClientId = (code: string) => { const key = `collab-client:${code}`; const value = localStorage.getItem(key); if (value) return value; const id = crypto.randomUUID(); localStorage.setItem(key, id); return id; };

export default function App() {
  const [form, setForm] = useState({ username: "", roomCode: "", passcode: "" });
  const [room, setRoom] = useState<RoomState | null>(null); const [error, setError] = useState("");
  const [connection, setConnection] = useState<"connected" | "reconnecting" | "disconnected">("disconnected");
  const [activities, setActivities] = useState<Activity[]>([]); const [typing, setTyping] = useState<string[]>([]); const [loading, setLoading] = useState(false); const [copied, setCopied] = useState(false);
  const socket = useRef<Socket | null>(null); const editor = useRef<Monaco.editor.IStandaloneCodeEditor | null>(null); const monaco = useRef<typeof Monaco | null>(null);
  const version = useRef(0); const suppress = useRef(false); const reconnecting = useRef(false); const session = useRef<Credentials | null>(null);
  const joinedRef = useRef<(reply: { ok: boolean; message?: string; room?: RoomState }) => void>(); const typingTimer = useRef<number>(); const cursorTimer = useRef<number>(); const changeTimer = useRef<number>(); const pendingCursor = useRef<Monaco.IPosition | null>(null); const pendingChanges = useRef<Change[]>([]); const decorations = useRef<Record<string, string[]>>({});
  const addActivity = useCallback((item: Activity) => setActivities((items) => [item, ...items].slice(0, 30)), []);
  const replaceDocument = useCallback((document: DocumentState) => { suppress.current = true; editor.current?.setValue(document.content); suppress.current = false; version.current = document.version; setRoom((current) => current ? { ...current, document } : current); }, []);
  const getSocket = useCallback(() => {
    if (socket.current) return socket.current;
    const next = io(serverUrl, { reconnection: true, reconnectionAttempts: 8 });
    next.on("connect", () => { setConnection("connected"); if (reconnecting.current && session.current && joinedRef.current) next.emit("room:join", session.current, joinedRef.current); });
    next.on("disconnect", () => { reconnecting.current = true; setConnection("reconnecting"); }); next.io.on("reconnect_attempt", () => setConnection("reconnecting")); next.io.on("reconnect_failed", () => setConnection("disconnected"));
    next.on("room:error", (event: { message: string }) => setError(event.message)); next.on("participants:update", (participants: Participant[]) => setRoom((current) => current ? { ...current, participants } : current)); next.on("activity", addActivity);
    next.on("typing", (event: { username: string; typing: boolean }) => setTyping((current) => event.typing ? [...new Set([...current, event.username])] : current.filter((name) => name !== event.username)));
    next.on("document:language", (language: string) => setRoom((current) => current ? { ...current, document: { ...current.document, language } } : current)); next.on("document:resync", replaceDocument);
    next.on("document:change", (event: { changes: Change[]; version: number }) => { const model = editor.current?.getModel(); if (!model || !editor.current) return; suppress.current = true; editor.current.executeEdits("remote", event.changes.map((change) => ({ range: offsetsToRange(model, change.rangeOffset, change.rangeLength), text: change.text }))); suppress.current = false; version.current = event.version; setRoom((current) => current ? { ...current, document: { ...current.document, content: model.getValue(), version: event.version } } : current); });
    next.on("cursor:update", (cursor: { clientId: string; username: string; lineNumber: number; column: number }) => { if (!editor.current || !monaco.current) return; decorations.current[cursor.clientId] = editor.current.deltaDecorations(decorations.current[cursor.clientId] ?? [], [{ range: new monaco.current.Range(cursor.lineNumber, cursor.column, cursor.lineNumber, cursor.column), options: { className: "remote-cursor", beforeContentClassName: "remote-cursor-line", after: { content: ` ${cursor.username}`, inlineClassName: "remote-cursor-label" } } }]); });
    socket.current = next; return next;
  }, [addActivity, replaceDocument]);
  const joined = useCallback((reply: { ok: boolean; message?: string; room?: RoomState }) => { setLoading(false); if (!reply.ok || !reply.room) { setError(reply.message ?? "Unable to enter room."); return; } reconnecting.current = false; version.current = reply.room.document.version; setRoom(reply.room); setError(""); addActivity({ message: `Connected to ${reply.room.code}.`, createdAt: new Date().toISOString() }); }, [addActivity]);
  joinedRef.current = joined;
  const enter = (event: "room:create" | "room:join") => { const roomCode = form.roomCode.trim(); if (!form.username.trim() || !roomCode) return setError("Enter a username and room ID."); setLoading(true); setError(""); const credentials = { ...form, roomCode, clientId: getClientId(roomCode) }; session.current = credentials; getSocket().emit(event, credentials, joined); };
  const leave = () => { socket.current?.disconnect(); socket.current = null; session.current = null; setRoom(null); setTyping([]); setActivities([]); setConnection("disconnected"); };
  const copyRoom = async () => { if (!room) return; await navigator.clipboard.writeText(room.code); setCopied(true); window.setTimeout(() => setCopied(false), 1500); };
  useEffect(() => () => { window.clearTimeout(changeTimer.current); window.clearTimeout(cursorTimer.current); window.clearTimeout(typingTimer.current); socket.current?.disconnect(); }, []);
  const mounted: OnMount = (instance, api) => { editor.current = instance; monaco.current = api; instance.onDidChangeCursorPosition((event) => moved(event.position)); if (room) replaceDocument(room.document); };
  const changed = (value: string | undefined, event: Monaco.editor.IModelContentChangedEvent) => { if (!room || suppress.current || value === undefined || !socket.current?.connected) return; pendingChanges.current.push(...event.changes.map(({ rangeOffset, rangeLength, text }) => ({ rangeOffset, rangeLength, text }))); if (!changeTimer.current) changeTimer.current = window.setTimeout(() => { const changes = pendingChanges.current.splice(0); changeTimer.current = undefined; if (changes.length && socket.current?.connected) { socket.current.emit("document:change", { version: version.current, changes }); version.current += 1; } }, 220); socket.current.emit("editing:start"); setRoom((current) => current ? { ...current, document: { ...current.document, content: value } } : current); socket.current.emit("typing", true); window.clearTimeout(typingTimer.current); typingTimer.current = window.setTimeout(() => socket.current?.emit("typing", false), 850); };
  const moved = (position: Monaco.IPosition | null) => { if (!position || !socket.current?.connected) return; pendingCursor.current = position; if (cursorTimer.current) return; cursorTimer.current = window.setTimeout(() => { if (pendingCursor.current) socket.current?.emit("cursor:update", pendingCursor.current); cursorTimer.current = undefined; }, 75); };
  if (!room) return <Lobby form={form} setForm={setForm} enter={enter} error={error} loading={loading} connection={connection} />;
  return <main className="app-shell"><header className="workspace-header"><div><p className="eyebrow">COLLABORATIVE CODE PAD</p><div className="room-title"><h1>{room.code}</h1><button className="ghost small" onClick={copyRoom}>{copied ? "Copied" : "Copy room ID"}</button></div></div><div className="toolbar"><Status state={connection} /><label className="language-label">Language<select value={room.document.language} onChange={(e) => socket.current?.emit("document:language", e.target.value)}>{[["javascript", "JavaScript"], ["python", "Python"], ["cpp", "C++"], ["java", "Java"]].map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><button className="ghost" onClick={leave}>Leave room</button></div></header><div className="workspace-grid"><section className="editor-panel"><Editor height="calc(100vh - 126px)" language={room.document.language} value={room.document.content} theme="vs-dark" loading={<div className="editor-loading">Loading editor…</div>} onMount={mounted} onChange={changed} options={{ minimap: { enabled: false }, fontSize: 14, automaticLayout: true, padding: { top: 16 } }} /></section><aside className="sidebar"><Panel title={`Participants · ${room.participants.length}`}>{room.participants.length ? room.participants.map((person) => <p key={person.clientId} className="participant"><span><i />{person.username}</span>{person.isHost && <span className="host">Host</span>}</p>) : <Empty>Waiting for teammates.</Empty>}</Panel><Panel title="Typing">{typing.length ? <p className="typing">{typing.join(", ")} {typing.length === 1 ? "is" : "are"} typing…</p> : <Empty>Nobody is typing.</Empty>}</Panel><Panel title="Activity">{activities.length ? activities.map((item, index) => <p className="activity" key={`${item.createdAt}-${index}`}>{item.message}</p>) : <Empty>Activity will appear here.</Empty>}</Panel></aside></div>{error && <div className="toast" role="alert">{error}</div>}</main>;
}
function Lobby({ form, setForm, enter, error, loading, connection }: { form: { username: string; roomCode: string; passcode: string }; setForm: React.Dispatch<React.SetStateAction<{ username: string; roomCode: string; passcode: string }>>; enter: (event: "room:create" | "room:join") => void; error: string; loading: boolean; connection: "connected" | "reconnecting" | "disconnected" }) { return <main className="lobby"><section className="hero"><p className="eyebrow">COLLABORATIVE WORKSPACE</p><h1>Start or join a code room.</h1><p>Use a room ID to work with your team in the same editor. Your local workspace is saved between server restarts.</p><Status state={connection} /></section><section className="lobby-card"><h2>Room access</h2><p className="muted">Enter a display name and room ID.</p><div className="form"><label>Display name<input autoComplete="name" placeholder="e.g. Ayush" value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })} /></label><label>Room ID<input placeholder="e.g. club-project" value={form.roomCode} onChange={(e) => setForm({ ...form, roomCode: e.target.value })} /></label><label>Passcode <span className="muted">(optional)</span><input type="password" placeholder="Only if the room uses one" value={form.passcode} onChange={(e) => setForm({ ...form, passcode: e.target.value })} /></label><p className="form-error" role="alert">{error}</p><div className="actions"><button disabled={loading} onClick={() => enter("room:create")}>{loading ? "Working…" : "Create room"}</button><button disabled={loading} className="ghost" onClick={() => enter("room:join")}>Join room</button></div></div></section></main>; }
function Status({ state }: { state: "connected" | "reconnecting" | "disconnected" }) { const text = state === "connected" ? "Connected" : state === "reconnecting" ? "Reconnecting" : "Offline"; return <span className={`status ${state}`}><i />{text}</span>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="panel"><h2>{title}</h2>{children}</section>; }
function Empty({ children }: { children: React.ReactNode }) { return <p className="empty">{children}</p>; }
function offsetsToRange(model: Monaco.editor.ITextModel, offset: number, length: number) { const start = model.getPositionAt(offset); const end = model.getPositionAt(offset + length); return { startLineNumber: start.lineNumber, startColumn: start.column, endLineNumber: end.lineNumber, endColumn: end.column }; }
